import { notFound } from "next/navigation"
import { createAdminClient } from "@/lib/supabase/admin"

interface PageProps {
  params: Promise<{ token: string }>
}

export default async function SharePage({ params }: PageProps) {
  const { token } = await params
  const admin = createAdminClient()

  const { data: link } = await admin
    .from("client_share_links")
    .select("report_id, expires_at, created_at")
    .eq("token", token)
    .maybeSingle()

  if (!link) {
    notFound()
  }

  if (link.expires_at && new Date(link.expires_at) < new Date()) {
    notFound()
  }

  const { data: report } = await admin
    .from("reports")
    .select("id, client_name, narrative_text, raw_data, period_start, period_end, created_at")
    .eq("id", link.report_id)
    .single()

  if (!report) {
    notFound()
  }

  const rawData = report.raw_data as Record<string, any> | null
  const metrics = rawData?.metrics as Record<string, any> | null

  const { data: reportConfig } = await admin
    .from("report_configs")
    .select("name, user_id")
    .eq("id", report.id)
    .maybeSingle()

  let brandSettings: Record<string, string> = {}
  if (reportConfig?.user_id) {
    const { data: profile } = await admin
      .from("profiles")
      .select("brand_settings")
      .eq("user_id", reportConfig.user_id)
      .maybeSingle()

    if (profile?.brand_settings) {
      brandSettings = profile.brand_settings as Record<string, string>
    }
  }

  const brandName = brandSettings.companyName || "Kvant"
  const primaryColor = brandSettings.primaryColor || "#27262E"
  const accentColor = brandSettings.accentColor || "#E19C63"
  const secondaryColor = brandSettings.secondaryColor || "#8BA5BE"

  return (
    <div style={{ "--primary": primaryColor, "--accent": accentColor, "--secondary": secondaryColor } as React.CSSProperties}>
      <style>{`
        :root {
          --brand-primary: ${primaryColor};
          --brand-accent: ${accentColor};
          --brand-secondary: ${secondaryColor};
        }
        body {
          margin: 0;
          font-family: "Inter", ui-sans-serif, system-ui, sans-serif;
          background: ${primaryColor};
          color: #F5F5F5;
        }
        * { box-sizing: border-box; }
      `}</style>

      <header style={{
        borderBottom: "1px solid rgba(255,255,255,0.08)",
        padding: "24px 32px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
      }}>
        <span style={{
          fontSize: "1.5rem",
          fontWeight: 700,
          color: accentColor,
          letterSpacing: "-0.02em",
        }}>
          {brandName}
        </span>
        <span style={{
          fontSize: "0.75rem",
          color: "#A0A0A0",
        }}>
          Generated by Kvant
        </span>
      </header>

      <main style={{
        maxWidth: "800px",
        margin: "0 auto",
        padding: "48px 24px",
      }}>
        <div style={{
          background: "rgba(39,38,46,0.6)",
          border: "1px solid rgba(255,255,255,0.08)",
          borderRadius: "12px",
          padding: "40px",
          backdropFilter: "blur(8px)",
        }}>
          <h1 style={{
            fontSize: "1.75rem",
            fontWeight: 700,
            margin: 0,
            color: "#F5F5F5",
          }}>
            {reportConfig?.name || "Performance Report"}
          </h1>

          <p style={{
            color: "#A0A0A0",
            fontSize: "0.875rem",
            marginTop: "8px",
          }}>
            Report for {report.client_name}
            {report.period_start ? ` — ${new Date(report.period_start).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}` : ""}
            {report.period_end ? ` to ${new Date(report.period_end).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}` : ""}
          </p>

          {metrics && (
            <div style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
              gap: "16px",
              marginTop: "32px",
              marginBottom: "32px",
            }}>
              {[
                { label: "Sessions", value: metrics.sessions?.toLocaleString() },
                { label: "Users", value: metrics.users?.toLocaleString() },
                { label: "Page Views", value: metrics.pageviews?.toLocaleString() },
                { label: "Bounce Rate", value: typeof metrics.bounceRate === "number" ? `${metrics.bounceRate}%` : undefined },
              ].filter(m => m.value).map((metric) => (
                <div key={metric.label} style={{
                  background: "rgba(139,181,190,0.1)",
                  border: "1px solid rgba(139,181,190,0.2)",
                  borderRadius: "8px",
                  padding: "16px",
                  textAlign: "center",
                }}>
                  <div style={{ fontSize: "0.75rem", color: secondaryColor, textTransform: "uppercase", letterSpacing: "0.05em" }}>
                    {metric.label}
                  </div>
                  <div style={{ fontSize: "1.5rem", fontWeight: 700, marginTop: "4px", color: "#F5F5F5" }}>
                    {metric.value}
                  </div>
                </div>
              ))}
            </div>
          )}

          {report.narrative_text && (
            <div
              dangerouslySetInnerHTML={{ __html: report.narrative_text.replace(/\n/g, "<br>") }}
              style={{
                lineHeight: "1.75",
                color: "#D0D0D0",
                fontSize: "0.9375rem",
                marginTop: metrics ? "16px" : "0",
              }}
            />
          )}

          {report.narrative_text && !report.narrative_text.includes("<") && (
            <div style={{
              lineHeight: "1.75",
              color: "#D0D0D0",
              fontSize: "0.9375rem",
              marginTop: "24px",
              whiteSpace: "pre-wrap",
            }}>
              {report.narrative_text}
            </div>
          )}
        </div>
      </main>

      <footer style={{
        borderTop: "1px solid rgba(255,255,255,0.08)",
        padding: "24px 32px",
        textAlign: "center",
        fontSize: "0.75rem",
        color: "#A0A0A0",
      }}>
        Generated by Kvant &mdash; {new Date(report.created_at).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
      </footer>
    </div>
  )
}
