const RESEND_API_KEY = process.env.RESEND_API_KEY

function isResendConfigured(): boolean {
  return !!RESEND_API_KEY && RESEND_API_KEY !== "your_resend_api_key"
}

function buildEmailHtml(reportData: any): string {
  const metrics = reportData.raw_data?.metrics || {}
  const rows: string[] = []

  if (metrics.sessions !== undefined) {
    rows.push(`
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#4B5563;font-size:13px;">Sessions</td>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#111827;font-size:13px;text-align:right;font-weight:600;">${metrics.sessions.toLocaleString()}</td>
      </tr>`)
  }
  if (metrics.users !== undefined) {
    rows.push(`
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#4B5563;font-size:13px;">Users</td>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#111827;font-size:13px;text-align:right;font-weight:600;">${metrics.users.toLocaleString()}</td>
      </tr>`)
  }
  if (metrics.pageviews !== undefined) {
    rows.push(`
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#4B5563;font-size:13px;">Pageviews</td>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#111827;font-size:13px;text-align:right;font-weight:600;">${metrics.pageviews.toLocaleString()}</td>
      </tr>`)
  }
  if (metrics.bounceRate !== undefined) {
    rows.push(`
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#4B5563;font-size:13px;">Bounce Rate</td>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#111827;font-size:13px;text-align:right;font-weight:600;">${metrics.bounceRate}%</td>
      </tr>`)
  }
  if (metrics.avgSessionDuration !== undefined) {
    rows.push(`
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#4B5563;font-size:13px;">Avg. Session Duration</td>
        <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#111827;font-size:13px;text-align:right;font-weight:600;">${metrics.avgSessionDuration}s</td>
      </tr>`)
  }

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body style="margin:0;padding:0;background-color:#F3F4F6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center" style="padding:40px 20px;">
        <table width="560" cellpadding="0" cellspacing="0" style="background-color:#FFFFFF;border-radius:8px;overflow:hidden;">
          <tr>
            <td style="background-color:#27262E;padding:24px 32px;">
              <h1 style="color:#E19C63;font-size:20px;margin:0;font-weight:700;">KVANT</h1>
              <p style="color:#FFFFFF;font-size:14px;margin:4px 0 0 0;">Narrative Report — ${reportData.client_name}</p>
            </td>
          </tr>
          <tr>
            <td style="padding:32px;">
              <h2 style="color:#111827;font-size:16px;font-weight:600;margin:0 0 16px 0;">Executive Summary</h2>
              <p style="color:#4B5563;font-size:13px;line-height:1.6;margin:0 0 24px 0;white-space:pre-wrap;">${reportData.narrative_text}</p>
              ${rows.length > 0 ? `
              <h2 style="color:#111827;font-size:16px;font-weight:600;margin:0 0 12px 0;">Performance Metrics</h2>
              <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #E5E7EB;border-radius:6px;overflow:hidden;">
                <tr>
                  <td style="background-color:#27262E;padding:10px 12px;color:#FFFFFF;font-size:13px;font-weight:600;">Metric</td>
                  <td style="background-color:#27262E;padding:10px 12px;color:#FFFFFF;font-size:13px;font-weight:600;text-align:right;">Value</td>
                </tr>
                ${rows.join("")}
              </table>` : ""}
            </td>
          </tr>
          <tr>
            <td style="background-color:#F9FAFB;padding:16px 32px;text-align:center;">
              <p style="color:#8BA5BE;font-size:11px;margin:0;">Generated by Kvant — AI-Powered Client Reports</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}

export async function sendReportEmail(recipients: string[], reportData: any): Promise<void> {
  if (!isResendConfigured()) {
    console.log("Email not sent: RESEND_API_KEY not configured")
    return
  }

  try {
    const { Resend } = await import("resend")
    const resend = new Resend(RESEND_API_KEY)

    const html = buildEmailHtml(reportData)

    await resend.emails.send({
      from: "Kvant Reports <reports@kvantio.vercel.app>",
      to: recipients,
      subject: `Narrative Report — ${reportData.client_name}`,
      html,
    })

    console.log(`Report email sent to ${recipients.length} recipient(s)`)
  } catch (error) {
    console.error("Failed to send report email:", error)
  }
}
